### ISSUE TITLE
layout without header instead of $store.setHeader=false

### ISSUE THREAD

**Issue by davewwww** [gitamgadtaula/vuetify-website#10]
https://github.com/gitamgadtaula/vuetify-website/blob/fcadffd9e85e3cfff1db188419a4955b26bc549d/components/Development.vue#L57

is it not easier to create a layout without a header image (eg. default_without_header.vue) instead of disable the header via store all the time?

**Comment by ShaileshAdhikari** [comment]
I don't think it is good idea to create multiple layouts. And it is good practice to hold some variable in store.
