### ISSUE TITLE
project image card as component?

### ISSUE THREAD

**Issue by davewwww** [gitamgadtaula/vuetify-website#11]
https://github.com/gitamgadtaula/vuetify-website/blob/fcadffd9e85e3cfff1db188419a4955b26bc549d/components/Development.vue#L15

is it not easier to create a reusable component (eg: project_list_item.vue or image_preview_item.vue) for this v-card to reuse it at all lists (projects, developmen, salons, etc?)

**Comment by ShaileshAdhikari** [comment]
Added a component image_list_flex.vue
