### ISSUE TITLE
Projekt Details

### ISSUE THREAD

**Issue by davewwww** [gitamgadtaula/vuetify-website#16]
- [ ] background image must be fullscreen
- [x] navbar background transparent

SHOULD:
![image](https://user-images.githubusercontent.com/921303/114203498-8441ab00-9958-11eb-96b7-6903c29fcce5.png)

IS:
![image](https://user-images.githubusercontent.com/921303/114203516-886dc880-9958-11eb-9d39-c784794fbb9d.png)

- [x] project items need space at the left and right side
SHOULD:
![image](https://user-images.githubusercontent.com/921303/114203723-b4894980-9958-11eb-9b48-9e0b364ec172.png)
IS:
![image](https://user-images.githubusercontent.com/921303/114203758-bc48ee00-9958-11eb-9204-06a6271668e0.png)

**Comment by ShaileshAdhikari** [comment]
Duplicate #14
