### ISSUE TITLE
Static pages

### ISSUE THREAD

**Issue by davewwww** [gitamgadtaula/vuetify-website#19]
- [ ] background image must be fullsize (at /leistung, /philosophie, /team)
- [x] image is linked at https://mundelarchitekten.de/wp-content/uploads/2018/06/colani.png - must be loaded from the project files

should:
![image](https://user-images.githubusercontent.com/921303/114204932-0aaabc80-995a-11eb-9919-039c209f1e8c.png)

IS:
![image](https://user-images.githubusercontent.com/921303/114204918-07173580-995a-11eb-8670-caef5a258780.png)

**Comment by ShaileshAdhikari** [comment]
Duplicate Issue #01 !
